### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_proceed_'

### ISSUE THREAD

**Issue by oammous** [pgiri/asyncoro#15]
I am using dispy which uses asyncoro (4.5.3) as a dependency.

I noticed that my nodes sometimes crash because of the following error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Anaconda\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Anaconda\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 3631, in _schedule
    self._notifier.poll(0)
  File "C:\Anaconda\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 1204, in poll
    overlap.object(err, n)
  File "C:\Anaconda\lib\site-packages\gulbis\ext\asyncoro\__init__.py", line 1430, in _recvall
    self._read_coro._proceed_('')
AttributeError: 'NoneType' object has no attribute '_proceed_'
```

**Comment by wsfax** [comment]
is this fixed in pycos? should i upgrade to pycos to get the fix?

**Comment by wsfax** [comment]
I did some debugging and found out that this due to the value of MsgTimeout which is hardcoded in dispy to 10 seconds. I increased this value and things went better.
do you have an explanation or any idea what might be wrong?
is there a way to change that value of MsgTimeout when I create my dispy client? not that I am not using a separate scheduler.

**Comment by wsfax** [comment]
update: @pgiri I am running my program with MsgTimeout set to 15 since 2 days and I have seen the issue since then.
