### ISSUE TITLE
finish() method on a RCI does not work 

### ISSUE THREAD

**Issue by ocurero** [pgiri/asyncoro#4]
server.py:

```
def faraway_proc(coro=None):
    logger.info("faraway started")
    yield coro.locate("farfaraway_proc", timeout=10)
    logger.info("faraway ended")
    
faraway = asyncoro.RCI(faraway_proc)
faraway.register()
[...]
```

client.py:

```
def client(coro=None):
    yield scheduler.peer(asyncoro.Location("127.0.0.2", 10001), udp_port=51350)
    rci1 = yield asyncoro.RCI.locate('faraway_proc')
    print "client rci1 start"
    rcoro = yield rci1()
    print "client rci1 running"
    value = yield rcoro.finish()
    print "client rci1 ended"
    print value
    
scheduler = asyncoro.AsynCoro(node="127.0.0.2", name="client1", tcp_port=2002)            
asyncoro.Coro(client)
```

With the above code, the following exception ocurrs:

```
2016-04-01 12:26:17,155 - asyncoro - network server "client1" @ 127.0.0.2:2002, udp_port=51350                                                                                      
faraway_proc@127.0.0.2:10001                                                            
client rci1 start                                                                         
client rci1 running                                                                       
2016-04-01 12:26:17,169 - asyncoro - uncaught exception in client/140369968107936@127.0.0.2:2002:                                                                                 
Traceback (most recent call last):                                                        
  File "/home/oscar/dev/projects/client/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 3327, in _schedule                                                              
    retval = coro._generator.throw(*exc)                                                  
  File "client.py", line 43, in client                                                    
    value = yield rcoro.finish()                                                              
  File "/home/oscar/dev/projects/client/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 3329, in _schedule                                                              
    retval = coro._generator.send(coro._value)                                            
  File "/home/oscar/dev/projects/client/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 2412, in finish                                                                 
    if self._complete is None:                                                            
AttributeError: _complete
```
faraway_proc works as expected:
```
2016-04-01 12:11:58,718 - asyncoro - network server "test1" @ 127.0.0.2:10001, udp_port=51350
INFO:asyncoro:network server "test1" @ 127.0.0.2:10001, udp_port=51350
INFO:server:Initialization completed
INFO:server:faraway started
INFO:server:faraway ended
```
Am I doing anything wrong?

Thanks!

**Comment by pgiri** [comment]
'finish' method works only for local coroutines (only some of coroutine methods work for remote coroutines). Instead, you can ask remote scheduler to send MonitorException; see 'rci_monitor_client.py' in examples.

**Comment by ocurero** [comment]
Thanks. I see that if my "faraway" coroutine finish after I have setted the monitor then it's ok. However, since my faraway coroutine will be very fast most of the time, the monitor fails because the coroutine has already finished. Is there another way of doing this?

I just need a query --> reponse pattern with a very small elapse time, but I'm not sure RCI is suited for this.

Cheers!

**Comment by ocurero** [comment]
(sorry for the double reply)

Looking at the example, I can simply pass the coro where I want to send the response. Doing it that way works fine except for the following exception:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 763, in run
  File "/home/oscar/dev/projects/client/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 3470, in _schedule
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute '_AsynCoro__cur_coro'
```

This exception doesn't throw if I just print "AsynCoro.__cur_coro", so it must be some synchronization issue.

**Comment by pgiri** [comment]
You can use message passing. Below are full programs (I can't comment on the error you mention without seeing the program).

Server:

   import asyncoro.disasyncoro as asyncoro

   def faraway_proc(client, coro=None):
       asyncoro.logger.info("faraway %s started for %s" % (coro, client))
       yield coro.sleep(0.2)
       client.send(coro)

   scheduler = asyncoro.AsynCoro(node='127.0.0.1', name="server", tcp_port=2001)
   faraway = asyncoro.RCI(faraway_proc)
   faraway.register()
   input()

Client:

   import asyncoro.disasyncoro as asyncoro

   def client(coro=None):
       # yield scheduler.peer(asyncoro.Location("127.0.0.1", 2001))
       rci_faraway = yield asyncoro.RCI.locate('faraway_proc')
       print("client %s started" % coro)
       rcoro = yield rci_faraway(coro)
       value = yield coro.receive()
       print('result: %s' % value)

   # scheduler = asyncoro.AsynCoro(node='127.0.0.1', name="client1", tcp_port=2002)
   asyncoro.Coro(client)

These are slightly modified from your programs above.

**Comment by ocurero** [comment]
Thanks, using message passing is simple and works fine :)

Last question regarding synchronization: do I need to sync the scheduler with my main thread before the program exits? I ask this because running your code from above sometimes doesn't work while others there's not error. For example:

_Ok:_
```
(src)oscar@hedera:~/dev/projects/python/src> python client.py 
2016-04-03 09:13:56,968 - asyncoro - network server "client1" @ 127.0.0.1:2002, udp_port=51350
client client/140606799524256@127.0.0.1:2002 started
result: faraway_proc/140147569021848@127.0.0.1:2001
```
_Ok:_
```
(src)oscar@hedera:~/dev/projects/python/src> python client.py 
2016-04-03 09:13:58,773 - asyncoro - network server "client1" @ 127.0.0.1:2002, udp_port=51350
client client/139738105606560@127.0.0.1:2002 started
result: faraway_proc/140147569021344@127.0.0.1:2001
```
_Fail:_
```
(src)oscar@hedera:~/dev/projects/python/src> python client.py 
2016-04-03 09:13:59,861 - asyncoro - network server "client1" @ 127.0.0.1:2002, udp_port=51350
client client/139783988101536@127.0.0.1:2002 started
result: faraway_proc/140147569021680@127.0.0.1:2001
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 763, in run
  File "/home/oscar/dev/projects/python/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 3279, in _schedule
  File "/home/oscar/dev/projects/python/src/lib/python2.7/site-packages/asyncoro/__init__.py", line 1709, in poll
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
```
Adding the following 3 lines at the bottom of the client main thread, seems to solve the error:
```
scheduler.join()
scheduler.terminate()
time.sleep(1)
```

**Comment by pgiri** [comment]
Which version of asyncoro are you using?

**Comment by ocurero** [comment]
Hi,

I'm using 3.6.13

Cheers,

**Comment by pgiri** [comment]
I thought this shouldn't happen with 3.6.13. I have tested your example again many times but couldn't reproduce error you get. Anyway, as suggested in 'discomp*' / 'discoro*' examples, you can wait for main coroutine to finish; i.e., replace last line in client with:

    asyncoro.Coro(client).value()

**Comment by pgiri** [comment]
While the above fix may work, can you try without that (i.e., without adding 'value()' to coroutine) after patching __init__.py with the attached fix?

[patch_exit.txt](https://github.com/pgiri/asyncoro/files/201355/patch_exit.txt)

**Comment by ocurero** [comment]
value() did nothing but your patch worked.

Thanks!

**Comment by pgiri** [comment]
This issue has been fixed as noted above.
