### ISSUE TITLE
Random exception using disasyncoro since version 4.1

### ISSUE THREAD

**Issue by ocurero** [pgiri/asyncoro#7]
Hi,

I'm randomly seeing this exception when two process comunicate each other through two definned channels. This only happens under version 4.1:  

```
2016-07-05 09:55:45 asyncoro - uncaught exception in !req_proc/140257477981584@127.0.0.1:10002:
Traceback (most recent call last):
  File "/home/oscar/dev/PythonEnvs/producction/lib/python2.7/site-packages/asyncoro/__init__.py", line 3649, in _schedule
    retval = coro._generator.send(coro._value)
 File "/home/oscar/dev/PythonEnvs/producction/lib/python2.7/site-packages/asyncoro/disasyncoro.py", line 183, in req_proc
    req = self.reqs.popleft()
IndexError: pop from an empty deque
```

Thanks!

**Comment by pgiri** [comment]
Can you attach (simple) test programs that exhibit this when run many times / long time?

**Comment by pgiri** [comment]
I committed 0db08b6..d894f29 to fix this. Please confirm if it solves your issue.

**Comment by ocurero** [comment]
After 30min I'm unable to reproduce the error, so IMHO we can mark this as fixed.

Thanks Giridhar!
